[features]
seeds = false
[programs.localnet]
exchange_market = "CUGAajqCMMGahDnsBKDkcUcejNKB8Jq2tebyje42mtmg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/dev/Downloads/exchange-market/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
