[features]
seeds = false
[programs.localnet]
exchange_market = "9B5paEycwyRhg8CeEsr4MUu42jbHYSkVJyGrn8zVQpd9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/dev/Downloads/exchange-market/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
