[features]
seeds = false
[programs.localnet]
exchange_market = "2ZtYYHQYffL7ZfbUJwMwY2hoVnqarwkqKBbz5wregkLR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
